apiVersion: apps/v1
kind: Deployment
metadata:
  name: wildfly
  labels:
    app: app
spec:
  template:
    metadata:
      name: wildfly
      labels:
        app: app
    spec:
      containers:
        - name: wildfly
          image: jboss/wildfly
          ports:
            - name: normaluser
              containerPort: 8080
            - name: admin
              containerPort: 9990
  replicas: 3
  selector:
    matchLabels:
      app: app
